In [1]:
import numpy as np

### Number of the weights we are looking to optimize.

In [15]:
num_weights = 3

### Input and Output

In [63]:
X=[[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
Y=[0,0,0,0,0,0,1,1]
X=np.array(X)
Y=np.array(Y)

### Defining the population size.
### Creating the initial population.

In [64]:
import numpy
sol_per_pop = 8
# Defining the population size.

pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.

#Creating the initial population.

new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)

### Calculating the fitness value of each solution in the current population.
### Fitness here indicates the error produced by each member in population

In [65]:
def cal_pop_fitness(pop):
     # Calculating the fitness value of each solution in the current population.
     # The fitness function calculates the sum of products between each input and its corresponding weight.
    fitness=np.zeros(len(pop))
    for i in range(len(pop)):
        err=0
        for j in range(len(X)):
            err += np.square(np.dot(X[j],pop[i])-Y[j])
        err/=len(X)
        fitness[i]=err
    print("Fitness values for each member in the current population")
    print(fitness)
    return fitness

### Selecting the best individuals in the current generation as parents for producing the offspring of the next generation

In [67]:
def select_mating_pool(pop, fitness, num_parents):

    # Selecting the best individuals in the current generation as parents for producing the offspring of the next generation.

    parents = numpy.empty((num_parents, pop.shape[1]))
    parentsidx=[]
    for parent_num in range(num_parents):

        max_fitness_idx = np.argmin(fitness)
        parentsidx.append(max_fitness_idx)

#         max_fitness_idx = max_fitness_idx[0][0]

        parents[parent_num, :] = pop[max_fitness_idx, :]

        fitness[max_fitness_idx] = 99999999999
    print("Top 4 members selected for crossover with indexes with min error values")
    print(parentsidx)

    return parents

# Crossover

In [68]:
def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # The point at which crossover takes place between two parents. Usually, it is at the center.
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        # Index of the first parent to mate.
        parent1_idx = k%parents.shape[0]
        # Index of the second parent to mate.
        parent2_idx = (k+1)%parents.shape[0]
        # The new offspring will have its first half of its genes taken from the first parent.
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # The new offspring will have its second half of its genes taken from the second parent.
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
#         print(offspring)
        return offspring

# Mutation

In [69]:
def mutation(offspring_crossover):

    # Mutation changes a single gene in each offspring randomly.

    for idx in range(offspring_crossover.shape[0]):

        # The random value to be added to the gene.

        random_value = numpy.random.uniform(-1.0, 1.0, 1)

        rnd=np.random.randint(offspring_crossover.shape[1])
        offspring_crossover[idx, rnd] = offspring_crossover[idx, rnd] + random_value
    print("4 new offspring generated after mutation")
    print(offspring_crossover)
    return offspring_crossover

# Repeat the below steps until the current population meets reaches desired goal

### 1)Population
### 2)Fitness calculation
### 3)Select best member for crossover
### 4)Crossover
### 5)Mutation
### 6)Offspring

In [70]:
num_generations = 5

num_parents_mating = 4
for generation in range(5):
    print("Generation",generation)
     # Measuring the fitness of each chromosome in the population.
    fitness = cal_pop_fitness(new_population)
    
    # Selecting the best parents in the population for mating.
    parents = select_mating_pool(new_population, fitness, num_parents_mating)

    # Generating next generation using crossover.
    offspring_crossover = crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # Adding some variations to the offsrping using mutation.
    offspring_mutation = mutation(offspring_crossover)
    
    # Creating the new population based on the parents and offspring.
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation
    print("Updated population")
    print(new_population)
    print('========================================================================================================')

Fitness values for each member in the current population
[ 8.31301093  3.33728678 23.60323247 14.21423059  3.0839614  10.69761682
 30.13585046  9.41281009]
Top 4 members selected for crossover with indexes
[4, 1, 0, 7]
4 new offspring generated after mutation
[[-1.96826660e+000  2.53496031e+000  1.00941357e+000]
 [ 3.40442145e-001  8.01097889e-307  5.13280910e-001]
 [ 6.03660751e-001 -5.00655365e-001  4.01851344e-001]
 [-6.81356303e-001 -5.00655365e-001  4.01851344e-001]]
Updated population
[[-1.11986745e+000  6.35093228e-001 -1.62406449e+000]
 [-2.18264693e+000  2.53496031e+000  1.00941357e+000]
 [-3.73570080e+000  3.26234730e+000 -1.37834487e+000]
 [ 3.39152671e+000  1.75125435e+000  5.67983810e-001]
 [-1.96826660e+000  2.53496031e+000  1.00941357e+000]
 [ 3.40442145e-001  8.01097889e-307  5.13280910e-001]
 [ 6.03660751e-001 -5.00655365e-001  4.01851344e-001]
 [-6.81356303e-001 -5.00655365e-001  4.01851344e-001]]
Fitness values for each member in the current population
[3.0839614  3.

In [76]:
print("Final population after 5 generations")
print(new_population)
scores=cal_pop_fitness(new_population)

Final population after 5 generations
[[ 3.40442145e-001  8.01097889e-307  5.13280910e-001]
 [ 6.03660751e-001 -5.00655365e-001  4.01851344e-001]
 [ 7.04026736e-001 -5.00655365e-001  4.01851344e-001]
 [ 3.40442145e-001 -5.00655365e-001  5.79677818e-001]
 [ 6.60326567e-001 -5.00655365e-001  4.01851344e-001]
 [-2.42813973e-001 -5.00655365e-001  4.01851344e-001]
 [ 5.62259135e-001 -5.00655365e-001  4.01851344e-001]
 [-1.00254305e-001 -5.00655365e-001 -1.59182939e-001]]
Fitness values for each member in the current population
[0.228509   0.3558912  0.3663736  0.40482055 0.36057132 0.66822228
 0.35450185 0.80619724]


In [79]:
print("Best member of the final population is final weight")
print(new_population[np.argmin(fitness)])
print("score =",scores[np.argmin(fitness)])

Best member
[ 0.34044215 -0.50065536  0.57967782]
score = 0.40482054788919647


In [81]:
print("Final weights")
weights=new_population[np.argmin(fitness)]
print(weights)

Final weights
[ 0.34044215 -0.50065536  0.57967782]


In [87]:
for i in range(len(X)):
    print("Input",X[i])
    print("Actual",Y[i])
    print("Predicted",np.dot(X[i],weights))
    

Input [0 0 0]
Actual 0
Predicted 0.0
Input [0 0 1]
Actual 0
Predicted 0.5796778181608329
Input [0 1 0]
Actual 0
Predicted -0.5006553646525063
Input [0 1 1]
Actual 0
Predicted 0.0790224535083266
Input [1 0 0]
Actual 0
Predicted 0.3404421452173825
Input [1 0 1]
Actual 0
Predicted 0.9201199633782153
Input [1 1 0]
Actual 1
Predicted -0.1602132194351238
Input [1 1 1]
Actual 1
Predicted 0.41946459872570907
