In [228]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [229]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [230]:
X = [0, 0, 0, 1, 1, 0, 1, 1]
X = np.reshape(X, (4, 2))
y_and = [-1, -1, -1, 1]
y_and = np.reshape(y_and, (4, 1))
y_or = [-1, 1, 1, 1]
y_or = np.reshape(y_or, (4, 1))

print(X)
print(X.shape)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 2)


In [231]:
def threshold(Z):
    for i in range(Z.shape[0]):
        if Z[i][0] > 0:
            Z[i][0] = 1
        else:
            Z[i][0] = -1
    return Z

In [232]:
def normalization(X):
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    X = (X - mean)/std
    return X

In [233]:
''' Back propagation implemetation '''

def backpropagation(w, b, X, Z, y, a):
    w = w - a*np.dot((Z - y).T, X)/Z.shape[0]
    b = b - a*np.sum(Z - y)/Z.shape[0]
    return w, b

In [234]:
'''Forward propagation implementation'''

def train(X, y, w, b, a, iters):
    for i in range(iters):
        Z = np.dot(X, w.T) + b
        Z = threshold(Z)
        w, b = backpropagation(w, b, X, Z, y, a)
    return w, b

In [235]:
def find_accuracy(X, Y, w, b):
    Z = np.dot(X, w.T) + b
    Z = threshold(Z)
    return accuracy_score(y_test, Z)

In [236]:
w = np.zeros(2)
w = np.expand_dims(w, axis=0)
b = -1
a = 0.1

'''AND gate implementation'''
print("AND gate implementation : ")
w, b = train(X, y_and, w, b, a, 6)
print("Bias : {}".format(b))
print("Weights : \n{}\n".format(w))
test = [1, 1]
ans = np.dot(test, w.T) + b
print(ans)

w = np.zeros(2)
w = np.expand_dims(w, axis=0)

''' OR gate implementation '''
print("OR gate implementation : ")
w, b = train(X, y_or, w, b, a, 6)
print("Bias : {}".format(b))
print("Weights : \n{}".format(w))

AND gate implementation : 
Bias : -0.6999999999999997
Weights : 
[[0.3 0.3]]

[-0.1]
OR gate implementation : 
Bias : -0.1999999999999997
Weights : 
[[0.3 0.3]]


In [237]:
''' Perceptron Training Algorithm with sample data '''

Data = pd.read_csv('/content/drive/My Drive/percep_data.csv')
Y = Data['Y']
X = Data[['X1', 'X2']]
X = normalization(X)
Y = np.expand_dims(Y, axis=1)
print("Shape of Y : {}".format(Y.shape))
print("Shape of X : {}".format(X.shape))

Shape of Y : (1000, 1)
Shape of X : (1000, 2)


In [238]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1, random_state = 42)

w = np.random.randn(1, 2)
b = np.random.randn()
print("Shape of weights : {}".format(w.shape))
print("Shape of x_train : {}, y_train : {}".format(x_train.shape, y_train.shape))
print(x_train)

Shape of weights : (1, 2)
Shape of x_train : (900, 2), y_train : (900, 1)
           X1        X2
716  1.698851  0.625282
351 -1.409669  1.409476
936  1.057688 -1.133713
256  0.745459  1.545916
635  1.230740  0.650181
..        ...       ...
106  0.882481  0.818460
270 -1.442591  0.311410
860 -0.963468 -0.862202
435 -1.417628 -0.112863
102  0.697162  1.217073

[900 rows x 2 columns]


In [239]:
w, b = train(np.array(x_train), np.array(y_train), w, b, a, 25)
accuracy = find_accuracy(np.array(x_test), np.array(y_test), w, b)
print("Accuracy of model : {}".format(accuracy))

Accuracy of model : 0.98
