In [1]:
# import statements
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from tqdm import tqdm

###### Activation Function
We use a sigmoid activation function

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

###### Backprop Function
We use a two layer network with variable number of input, hidden, and output units.

In [3]:
def backprop(X, Y, n_hid, lr = 0.2, w_init=None, n_iters=1, batch=False):
    # append ones col to X
    ones_col = np.ones((X.shape[0],1))
    X = np.concatenate((ones_col,X), axis=1)
    
    # create weights - if no init given, we randomise
    if w_init is not None:
        w1 = np.ones((n_hid,X.shape[1])) * w_init
        w2 = np.ones((Y.shape[1],n_hid+1)) * w_init
    else:
        w1 = np.random.randn(n_hid,X.shape[1]) / 10
        w2 = np.random.randn(Y.shape[1],n_hid+1) / 10
    
    history_w1 = []
    history_w2 = []
    
    # loop over number of iterations
    for i in tqdm(range(n_iters)):
        print(f"\n\n--------ITERATION {i+1}:-----------") 
        
        # for each training example 
        for idx, (x,y) in enumerate(zip(X,Y)):
            print(f"\n\nTRAINING EXAMPLE {idx+1}:\n")
            ### FORWARD PASS
            h = sigmoid(x.dot(w1.T))
            print(f"O(h1), O(h2) => {h}")
            
            temp_h = np.append(np.ones(1), h)
            o = sigmoid(temp_h.dot(w2.T))
            print(f"O(o)         => {o}")
            
            
            ### BACKWARD PASS
            do = o*(1-o)*(y-o)
            print(f"d(o)         => {do}")
                        
            dh = h * (1-h) * do.dot(w2[:,1:])
            print(f"d(h1), d(h2) => {dh}")
            
            
            ### WEIGHT CHANGES
            dw2 = lr * do * temp_h
            print(f"\nd(wh0), d(wh1), d(wh2) => {dw2}")
            
            dw1 = lr * dh.reshape(-1,1) *(x) 
            print("[d(w10), d(w11), d(w12)],\n[d(w20), d(w21), d(w22)]")
            print(dw1)
            
            # store deltas if batch
            if batch == True:
                history_w1.append(dw1)
                history_w2.append(dw2)
            
            # otherwise stochastic update -> update here
            else:
                ### WEIGHT UPDATES
                w2 += dw2
                print(f"\nwh0, wh1, wh2 => {w2}")
                w1 += dw1
                print("[w10, w11, w12],\n[w20, w21, w22]")
                print(w1)
                
        # for bacth update -> update here
        if batch is True:
            print("\nUpdated Weights:")
            w2 += sum(history_w2)
            w1 += sum(history_w1)
            
            print(f"wh0, wh1, wh2 => {w2}")
            print("[w10, w11, w12],\n[w20, w21, w22]")
            print(w1)
            
    
    

###### Running:
Just change values as required up to and including TT, and let the code do the rest B^)

In [4]:
w_init = 0.2                 # weight initiliaser (set to None for random but he wont ask this)
n_hid = 2                    # number of hidden units
lr = 0.2                     # learning rate
n_iters = 8                  # number of iterations / epochs
batch = False                 # if true, algo uses batch update.
TT = np.asarray([[0,0,1],    # Truth table
                [0,1,0], 
                [1,0,0],
                [1,1,1]])


X = TT[:,:2]
y = TT[:,2:]
backprop(X,y,n_hid,lr,w_init,n_iters,batch)

 38%|███▊      | 3/8 [00:00<00:00, 29.49it/s]



--------ITERATION 1:-----------


TRAINING EXAMPLE 1:

O(h1), O(h2) => [0.549834 0.549834]
O(o)         => [0.60346736]
d(o)         => [0.09488808]
d(h1), d(h2) => [0.00469727 0.00469727]

d(wh0), d(wh1), d(wh2) => [0.01897762 0.01043454 0.01043454]
[d(w10), d(w11), d(w12)],
[d(w20), d(w21), d(w22)]
[[0.00093945 0.         0.        ]
 [0.00093945 0.         0.        ]]

wh0, wh1, wh2 => [[0.21897762 0.21043454 0.21043454]]
[w10, w11, w12],
[w20, w21, w22]
[[0.20093945 0.2        0.2       ]
 [0.20093945 0.2        0.2       ]]


TRAINING EXAMPLE 2:

O(h1), O(h2) => [0.59891335 0.59891335]
O(o)         => [0.61563029]
d(o)         => [-0.14567637]
d(h1), d(h2) => [-0.00736391 -0.00736391]

d(wh0), d(wh1), d(wh2) => [-0.02913527 -0.0174495  -0.0174495 ]
[d(w10), d(w11), d(w12)],
[d(w20), d(w21), d(w22)]
[[-0.00147278 -0.         -0.00147278]
 [-0.00147278 -0.         -0.00147278]]

wh0, wh1, wh2 => [[0.18984234 0.19298503 0.19298503]]
[w10, w11, w12],
[w20, w21, w22]
[[0.19946667 0.

100%|██████████| 8/8 [00:00<00:00, 29.92it/s]



wh0, wh1, wh2 => [[0.07999526 0.12707517 0.12707517]]
[w10, w11, w12],
[w20, w21, w22]
[[0.19427091 0.19675647 0.19597114]
 [0.19427091 0.19675647 0.19597114]]


TRAINING EXAMPLE 4:

O(h1), O(h2) => [0.64267617 0.64267617]
O(o)         => [0.56053451]
d(o)         => [0.10825598]
d(h1), d(h2) => [0.00315912 0.00315912]

d(wh0), d(wh1), d(wh2) => [0.0216512  0.01391471 0.01391471]
[d(w10), d(w11), d(w12)],
[d(w20), d(w21), d(w22)]
[[0.00063182 0.00063182 0.00063182]
 [0.00063182 0.00063182 0.00063182]]

wh0, wh1, wh2 => [[0.10164646 0.14098988 0.14098988]]
[w10, w11, w12],
[w20, w21, w22]
[[0.19490274 0.1973883  0.19660296]
 [0.19490274 0.1973883  0.19660296]]


--------ITERATION 7:-----------


TRAINING EXAMPLE 1:

O(h1), O(h2) => [0.54857202 0.54857202]
O(o)         => [0.56373457]
d(o)         => [0.10729421]
d(h1), d(h2) => [0.00374616 0.00374616]

d(wh0), d(wh1), d(wh2) => [0.02145884 0.01177172 0.01177172]
[d(w10), d(w11), d(w12)],
[d(w20), d(w21), d(w22)]
[[0.00074923 0.       